=== JuanAn6/dam_m06/Projects/library.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT library (counter,cards)>
<!ATTLIST library
    name CDATA #REQUIRED
>
<!ELEMENT counter (#PCDATA)>
<!ELEMENT cards (bookCard|magazinCard)*>
<!ELEMENT bookCard (title,isLent?,creationDate,modificationDate?,editorial?)>
<!ATTLIST bookCard
    reference ID #REQUIRED
    order CDATA #REQUIRED
    isbn CDATA #REQUIRED
>
<!ELEMENT magazinCard (title,isLent?,creationDate,modificationDate?)>
<!ATTLIST magazinCard
    reference ID #REQUIRED
    order CDATA #REQUIRED
    year CDATA #REQUIRED
    num CDATA #REQUIRED
  >
<!ELEMENT title (#PCDATA)>
<!ELEMENT isLent (#PCDATA)>
<!ELEMENT creationDate (#PCDATA)>
<!ELEMENT modificationDate (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>

<!-- Observacions de format:
- Dates en format yyyy-mm-dd hh:mm:ss.milèssimesDeSegon
- Booleans amb valor Y o N
- referencia sempre començarà amb "r"
-->

=== JuanAn6/dam_m06/Projects/20241017_BPFitxerXmlJAXB/books_creat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "./library.dtd">
<library name="Juan">
    <counter>3</counter>
    <cards>
        <magazinCard year="2000" num="15" order="2" reference="r1111111111">
            <title>Tiempo</title>
            <creationDate>23/10/2024 15:36:34.684</creationDate>
        </magazinCard>
        <bookCard isbn="" order="1" reference="r2222222222">
            <title>El Quixot</title>
            <creationDate>23/10/2024 15:36:34.683</creationDate>
        </bookCard>
        <magazinCard year="2010" num="3" order="3" reference="r3333333333">
            <title>Mundo Cient√≠fico</title>
            <creationDate>23/10/2024 15:36:34.684</creationDate>
        </magazinCard>
    </cards>
</library>

=== JuanAn6/dam_m06/Projects/librarySkeleton.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library name="...">
    <counter>...</counter>
    <cards>
        <bookCard reference="r1.." order="..." isbn="...">
            <title>...</title>
            <isLent>...</isLent>                  
            <creationDate>...</creationDate>          
            <editorial>...</editorial>            
        </bookCard> 
        <magazinCard reference="r2.." order="..." year="..." num="...">
            <title>...</title>
            <creationDate>...</creationDate>          
            <modificationDate>...</modificationDate>
        </magazinCard> 
    </cards>
</library>

<!-- Observacions de format:
- Dates en format yyyy-mm-dd hh:mm:ss.milèssimesDeSegon
- Booleans amb valor Y o N
- referencia sempre començarà amb "r"
-->

=== JuanAn6/dam_m06/Projects/20241012_BPFitxerXmlJDom/books_creat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "../library.dtd">
<library name="Juan">
  <counter>3</counter>
  <cards>
    <magazinCard reference="r1111111111" order="2" year="2000" num="15">
      <title>Tiempo</title>
      <isLent>N</isLent>
      <creationDate>2024-10-13 11:25:56.005</creationDate>
      <modificationDate>N</modificationDate>
    </magazinCard>
    <bookCard isbn="" reference="r2222222222" order="1">
      <title>El Quixot</title>
      <isLent>N</isLent>
      <creationDate>2024-10-13 11:25:56.005</creationDate>
      <modificationDate>N</modificationDate>
      <editorial>N</editorial>
    </bookCard>
    <magazinCard reference="r3333333333" order="3" year="2010" num="3">
      <title>Mundo Cient√≠fico</title>
      <isLent>N</isLent>
      <creationDate>2024-10-13 11:25:56.005</creationDate>
      <modificationDate>N</modificationDate>
    </magazinCard>
  </cards>
</library>
