=== JuanAn6/dam_m06/Projects/GarciaJimenezJuanAntonio/FleetListPersistence.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT flotes (flota)*>
<!ELEMENT flota (autobus|taxi)*>
<!ATTLIST flota
  nom CDATA #REQUIRED>
<!ELEMENT autobus (potenciaFiscal,matricula?,dataMatricula?,places)*>
<!ATTLIST autobus
 identificadorBastidor ID #REQUIRED
 ecologic CDATA #REQUIRED>
<!ELEMENT taxi (potenciaFiscal,matricula?,dataMatricula?,llicencia)*>
<!ATTLIST taxi
 identificadorBastidor ID #REQUIRED
 ecologic CDATA #REQUIRED>
<!ELEMENT potenciaFiscal (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT dataMatricula (#PCDATA)>
<!ELEMENT places (#PCDATA)>
<!ELEMENT llicencia (#PCDATA)>

<!-- Requeriments addicionals:
Atribut identificadorBastidor amb prefix "IB-"
Dates en format yyyy/mm/dd
Atribut ecologic amb valors "Si","No"
-->

=== JuanAn6/dam_m06/Projects/GarciaJimenezJuanAntonio/llistaFlotes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE flotes SYSTEM "FleetListPersistence.dtd">
<flotes>
  <flota nom="Autobusos Gotera">
    <autobus identificadorBastidor="IB-12345678901234561" ecologic="No">
      <potenciaFiscal>20.5</potenciaFiscal>
      <matricula>1111BBB</matricula>
      <dataMatricula>2010-12-25</dataMatricula>
      <places>55</places>
    </autobus>
    <taxi identificadorBastidor="IB-12345678901234562" ecologic="Si">
      <potenciaFiscal>13.5</potenciaFiscal>
      <matricula>2222CCC</matricula>
      <dataMatricula>2012-11-24</dataMatricula>
      <llicencia>ARG123</llicencia>
    </taxi>
    <autobus identificadorBastidor="IB-12345678901234563" ecologic="Si">
      <potenciaFiscal>22.5</potenciaFiscal>
      <places>70</places>
    </autobus>
    <taxi identificadorBastidor="IB-12345678901234564" ecologic="No">
      <potenciaFiscal>15.9</potenciaFiscal>
      <llicencia>QTE123</llicencia>
    </taxi>
  </flota>
  <flota nom="Busos Averiats" />
  <flota nom="Mortadelo Busos">
    <autobus identificadorBastidor="IB-32345678901234561" ecologic="No">
      <potenciaFiscal>20.5</potenciaFiscal>
      <matricula>1111ZZZ</matricula>
      <dataMatricula>2010-12-25</dataMatricula>
      <places>55</places>
    </autobus>
    <taxi identificadorBastidor="IB-32345678901234562" ecologic="Si">
      <potenciaFiscal>13.5</potenciaFiscal>
      <matricula>2222YYY</matricula>
      <dataMatricula>2012-11-24</dataMatricula>
      <llicencia>ARG123</llicencia>
    </taxi>
    <autobus identificadorBastidor="IB-32345678901234563" ecologic="Si">
      <potenciaFiscal>22.5</potenciaFiscal>
      <places>70</places>
    </autobus>
    <taxi identificadorBastidor="IB-32345678901234564" ecologic="No">
      <potenciaFiscal>15.9</potenciaFiscal>
      <llicencia>QTE123</llicencia>
    </taxi>
  </flota>
</flotes>
